// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Chain {
    #[prost(enumeration = "super::super::super::blockchain::v1::Chain", tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Asset {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "super::super::super::blockchain::v1::Chain", tag = "2")]
    pub chain: i32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub metadata: ::core::option::Option<AssetMetadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssetMetadata {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub decimals: u32,
    #[prost(oneof = "asset_metadata::Metadata", tags = "3, 4")]
    pub metadata: ::core::option::Option<asset_metadata::Metadata>,
}
/// Nested message and enum types in `AssetMetadata`.
pub mod asset_metadata {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Metadata {
        #[prost(message, tag = "3")]
        Evm(super::AssetMetadataEvm),
        #[prost(message, tag = "4")]
        Svm(super::AssetMetadataSvm),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssetMetadataEvm {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssetMetadataSvm {}
