// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Block {
    #[prost(message, optional, tag = "1")]
    pub info: ::core::option::Option<super::Block>,
    #[prost(oneof = "block::Transactions", tags = "2")]
    pub transactions: ::core::option::Option<block::Transactions>,
}
/// Nested message and enum types in `Block`.
pub mod block {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Transactions {
        #[prost(message, tag = "2")]
        EvmTransactions(super::EvmTransactions),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EvmTransactions {
    #[prost(bytes = "vec", tag = "1")]
    pub serialized_txs: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub serialized_receipts: ::prost::alloc::vec::Vec<u8>,
}
