// This file is @generated by prost-build.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Chain {
    Unspecified = 0,
    Any = 1,
    AnyBtc = 2,
    AnyEvm = 3,
    AnySvm = 4,
    BtcBitcoin = 31,
    EvmEthereum = 41,
    EvmArbitrum = 42,
    EvmPolygon = 43,
    EvmUnichain = 44,
    SvmSolana = 76,
}
impl Chain {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CHAIN_UNSPECIFIED",
            Self::Any => "CHAIN_ANY",
            Self::AnyBtc => "CHAIN_ANY_BTC",
            Self::AnyEvm => "CHAIN_ANY_EVM",
            Self::AnySvm => "CHAIN_ANY_SVM",
            Self::BtcBitcoin => "CHAIN_BTC_BITCOIN",
            Self::EvmEthereum => "CHAIN_EVM_ETHEREUM",
            Self::EvmArbitrum => "CHAIN_EVM_ARBITRUM",
            Self::EvmPolygon => "CHAIN_EVM_POLYGON",
            Self::EvmUnichain => "CHAIN_EVM_UNICHAIN",
            Self::SvmSolana => "CHAIN_SVM_SOLANA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHAIN_UNSPECIFIED" => Some(Self::Unspecified),
            "CHAIN_ANY" => Some(Self::Any),
            "CHAIN_ANY_BTC" => Some(Self::AnyBtc),
            "CHAIN_ANY_EVM" => Some(Self::AnyEvm),
            "CHAIN_ANY_SVM" => Some(Self::AnySvm),
            "CHAIN_BTC_BITCOIN" => Some(Self::BtcBitcoin),
            "CHAIN_EVM_ETHEREUM" => Some(Self::EvmEthereum),
            "CHAIN_EVM_ARBITRUM" => Some(Self::EvmArbitrum),
            "CHAIN_EVM_POLYGON" => Some(Self::EvmPolygon),
            "CHAIN_EVM_UNICHAIN" => Some(Self::EvmUnichain),
            "CHAIN_SVM_SOLANA" => Some(Self::SvmSolana),
            _ => None,
        }
    }
}
