// This file is @generated by prost-build.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ChainId {
    Unspecified = 0,
    Any = 1,
    AnyBtc = 2,
    AnyEvm = 3,
    AnySvm = 4,
    BtcBitcoin = 31,
    EvmEthereum = 41,
    EvmArbitrum = 42,
    EvmPolygon = 43,
    EvmUnichain = 44,
    SvmSolana = 76,
}
impl ChainId {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CHAIN_ID_UNSPECIFIED",
            Self::Any => "CHAIN_ID_ANY",
            Self::AnyBtc => "CHAIN_ID_ANY_BTC",
            Self::AnyEvm => "CHAIN_ID_ANY_EVM",
            Self::AnySvm => "CHAIN_ID_ANY_SVM",
            Self::BtcBitcoin => "CHAIN_ID_BTC_BITCOIN",
            Self::EvmEthereum => "CHAIN_ID_EVM_ETHEREUM",
            Self::EvmArbitrum => "CHAIN_ID_EVM_ARBITRUM",
            Self::EvmPolygon => "CHAIN_ID_EVM_POLYGON",
            Self::EvmUnichain => "CHAIN_ID_EVM_UNICHAIN",
            Self::SvmSolana => "CHAIN_ID_SVM_SOLANA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHAIN_ID_UNSPECIFIED" => Some(Self::Unspecified),
            "CHAIN_ID_ANY" => Some(Self::Any),
            "CHAIN_ID_ANY_BTC" => Some(Self::AnyBtc),
            "CHAIN_ID_ANY_EVM" => Some(Self::AnyEvm),
            "CHAIN_ID_ANY_SVM" => Some(Self::AnySvm),
            "CHAIN_ID_BTC_BITCOIN" => Some(Self::BtcBitcoin),
            "CHAIN_ID_EVM_ETHEREUM" => Some(Self::EvmEthereum),
            "CHAIN_ID_EVM_ARBITRUM" => Some(Self::EvmArbitrum),
            "CHAIN_ID_EVM_POLYGON" => Some(Self::EvmPolygon),
            "CHAIN_ID_EVM_UNICHAIN" => Some(Self::EvmUnichain),
            "CHAIN_ID_SVM_SOLANA" => Some(Self::SvmSolana),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Asset {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "ChainId", tag = "2")]
    pub chain: i32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub metadata: ::core::option::Option<AssetMetadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssetMetadata {
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub decimals: u32,
    #[prost(oneof = "asset_metadata::Metadata", tags = "3, 4")]
    pub metadata: ::core::option::Option<asset_metadata::Metadata>,
}
/// Nested message and enum types in `AssetMetadata`.
pub mod asset_metadata {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Metadata {
        #[prost(message, tag = "3")]
        Evm(super::AssetMetadataEvm),
        #[prost(message, tag = "4")]
        Svm(super::AssetMetadataSvm),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssetMetadataEvm {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssetMetadataSvm {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Chain {
    #[prost(enumeration = "ChainId", tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
