// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParsedBlock {
    #[prost(message, optional, tag = "1")]
    pub info: ::core::option::Option<super::Block>,
    #[prost(message, repeated, tag = "2")]
    pub transfers: ::prost::alloc::vec::Vec<ParsedTransfer>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ParsedTransfer {
    #[prost(string, tag = "1")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub to: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub index: u64,
    #[prost(oneof = "parsed_transfer::Kind", tags = "6, 7")]
    pub kind: ::core::option::Option<parsed_transfer::Kind>,
}
/// Nested message and enum types in `ParsedTransfer`.
pub mod parsed_transfer {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(bool, tag = "6")]
        Native(bool),
        #[prost(string, tag = "7")]
        Contract(::prost::alloc::string::String),
    }
}
