// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Block {
    #[prost(enumeration = "Chain", tag = "1")]
    pub chain: i32,
    #[prost(enumeration = "ConfirmationLevel", tag = "2")]
    pub confirmation_level: i32,
    #[prost(uint64, tag = "3")]
    pub block_number: u64,
    #[prost(oneof = "block::Transactions", tags = "4")]
    pub transactions: ::core::option::Option<block::Transactions>,
}
/// Nested message and enum types in `Block`.
pub mod block {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Transactions {
        #[prost(bytes, tag = "4")]
        SerializedTxs(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Chain {
    Unspecified = 0,
    Evm = 1,
}
impl Chain {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CHAIN_UNSPECIFIED",
            Self::Evm => "CHAIN_EVM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHAIN_UNSPECIFIED" => Some(Self::Unspecified),
            "CHAIN_EVM" => Some(Self::Evm),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConfirmationLevel {
    Unspecified = 0,
    Pending = 1,
    Safe = 2,
    Finalized = 3,
}
impl ConfirmationLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CONFIRMATION_LEVEL_UNSPECIFIED",
            Self::Pending => "CONFIRMATION_LEVEL_PENDING",
            Self::Safe => "CONFIRMATION_LEVEL_SAFE",
            Self::Finalized => "CONFIRMATION_LEVEL_FINALIZED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CONFIRMATION_LEVEL_UNSPECIFIED" => Some(Self::Unspecified),
            "CONFIRMATION_LEVEL_PENDING" => Some(Self::Pending),
            "CONFIRMATION_LEVEL_SAFE" => Some(Self::Safe),
            "CONFIRMATION_LEVEL_FINALIZED" => Some(Self::Finalized),
            _ => None,
        }
    }
}
