// This file is @generated by prost-build.
pub mod cpay {
    pub mod api {
        pub mod v1 {
            pub mod blockchain {
                include!("cpay.api.v1.blockchain.rs");
            }
            pub mod kms {
                include!("cpay.api.v1.kms.rs");
            }
            pub mod merchant {
                include!("cpay.api.v1.merchant.rs");
            }
        }
    }
}
