// This file is @generated by prost-build.
pub mod cpay {
    pub mod api {
        pub mod v1 {
            pub mod kms {
                include!("cpay.api.v1.kms.rs");
            }
            pub mod merchant {
                include!("cpay.api.v1.merchant.rs");
            }
            pub mod wallet {
                include!("cpay.api.v1.wallet.rs");
            }
        }
    }
    pub mod blockchain {
        pub mod v1 {
            include!("cpay.blockchain.v1.rs");
            pub mod indexer {
                include!("cpay.blockchain.v1.indexer.rs");
            }
        }
    }
}
